{% set version = "3.6.2.2" %}

package:
  name: phreeqc4rkt
  version: {{ version }}

source:
  url: https://github.com/reaktoro/phreeqc4rkt/archive/v{{ version }}.tar.gz
  sha256: b1b81b030d051f796e82754ba979443e601a063f4b94a743b00ef4352404fa85

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/

about:
  home: https://github.com/reaktoro/phreeqc4rkt
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: phreeqc4rkt - a fork of phreeqc with minor changes to be used in Reaktoro
  doc_url: https://github.com/reaktoro/phreeqc4rkt
  dev_url: https://github.com/reaktoro/phreeqc4rkt

extra:
  recipe-maintainers:
    - allanleal
