{% set version = "3.8.6.0" %}

package:
  name: phreeqc4rkt
  version: {{ version }}

source:
  url: https://github.com/reaktoro/phreeqc4rkt/archive/v{{ version }}.tar.gz
  sha256: 96cfecae219424f27336876a0579466edeaa04b7374f16d1200452e8c16561ce

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/

about:
  home: https://github.com/reaktoro/phreeqc4rkt
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: phreeqc4rkt - a fork of phreeqc with minor changes to be used in Reaktoro
  doc_url: https://github.com/reaktoro/phreeqc4rkt
  dev_url: https://github.com/reaktoro/phreeqc4rkt

extra:
  recipe-maintainers:
    - allanleal
